
'use server';
/**
 * @fileOverview A simple, rule-based chatbot flow.
 *
 * - chat - A function that handles the chat interaction based on keywords.
 */

// A map of keywords to canned responses.
// The keys are regex patterns to match against the user's message.
const cannedResponses: { [key: string]: string } = {
    'shopify': `We are Shopify experts who build high-converting e-commerce experiences. Our services include:\n\n• Custom Store Design & Theme Customization\n• App Integration & Custom Development\n• Conversion Rate Optimization (CRO)\n• Migration to Shopify\n• Ongoing Support & Maintenance\n\nWe build stunning storefronts and powerful back-end solutions that sell. Learn more at /shopify.`,
    'social media': `Our Social Media Marketing services help you build and nurture online communities. We offer:\n\n• Social-First Strategy Development\n• Platform Management (Instagram, Facebook, LinkedIn, etc.)\n• Community Building & Engagement\n• Campaign Creation & Execution\n• Social Listening & Brand Positioning\n\nWe create content that connects and run targeted ad campaigns to expand your reach. You can learn more at /social-media.`,
    'creative|branding': `We craft unforgettable brand identities. Our Creative & Branding services include:\n\n• Brand Strategy & Positioning\n• Logo Design & Visual Identity\n• Full-Service Production (Photo & Video)\n• Copywriting & Brand Voice\n\nWe build brands with soul. Learn more at /creative-branding.`,
    'b2b marketing': `We drive meaningful engagement and growth with strategic B2B marketing solutions. Our core services are:\n\n• Account-Based Marketing (ABM)\n• Lead Generation & Nurturing\n• B2B Content Strategy\n• Marketing & Sales Analytics\n\nWe connect you with your ideal customers. See more at /b2b.`,
    'search marketing|seo|sem': `We help you dominate search engine results. Our Search Marketing services combine:\n\n• Search Engine Optimization (SEO) to climb rankings organically.\n• Search Engine Marketing (SEM) for immediate impact with Pay-Per-Click (PPC) ads.\n\nWe increase your visibility and drive targeted traffic. Explore more at /search-marketing.`,
    'video production': `We create compelling video content from concept to completion. Our services include:\n\n• Concept & Scriptwriting\n• On-Location & Studio Filming\n• Post-Production & Editing\n• Animation & Motion Graphics\n\nWe tell your story through video. See our work at /video-production.`,
    'online reputation management|orm': `We shape your brand’s narrative and protect your online image. Our services include:\n\n• Reputation Monitoring\n• Review Management\n• Brand Image Building\n• Crisis Response\n\nWe help you control your digital narrative. Learn more at /online-reputation-management.`,
    'ecommerce|e-commerce': `We build beautiful, high-performing e-commerce websites that turn visitors into loyal customers. We specialize in:\n\n• Custom Storefront Design\n• Platform Expertise (Shopify & WooCommerce)\n• Mobile-First and Responsive Design\n• Conversion Rate Optimization (CRO)\n\nWe build digital flagships. See more at /ecommerce-development.`,
    'website development|web solutions': `We build high-performance websites engineered for performance, security, and scalability. Our process includes:\n\n• Discovery & Planning\n• UI/UX Design\n• Development & Testing\n• Launch & Support\n\nWe also build custom web applications and work with Content Management Systems (CMS). Learn more at /web-solutions.`,
    'mobile app': `We build intuitive, high-performance native iOS & Android apps that engage users and drive growth. Our full-service process covers:\n\n• Strategy & UI/UX Design\n• Agile Development & QA\n• App Store Deployment\n• Ongoing Support\n\nWe bring your vision to the palm of their hand. See our approach at /mobile-app-development.`,
    'augmented reality': `We craft AR experiences that captivate, engage, and convert, blurring the lines between digital and reality. Our AR services include:\n\n• Immersive 3D Models\n• WebAR & App-Based Solutions\n• Custom Social Media Filters\n• Interactive Animations\n\nStep into the future with us at /augmented-reality.`,
    'gtm strategy|go-to-market': `We turn great ideas into market-leading products with our comprehensive Go-To-Market (GTM) strategy, a roadmap designed to successfully launch and scale your venture. Our phases include research, positioning, pre-launch buzz, launch execution, and growth optimization. Plan your launch at /gtm-strategy.`,
    'performance marketing': `Drive growth and maximize your ROI with our data-driven performance marketing strategies. We focus on measurable results through:\n\n• Paid Search Advertising (PPC)\n• Social Media Advertising\n• Conversion Rate Optimization (CRO)\n\nSee how we deliver tangible results at /performance-marketing.`,
    'rapid website': `Launch your online presence in record time. Our rapid development service is ideal for startups, marketing campaigns, and MVPs. We use customizable templates to deliver high-quality, responsive websites quickly. Get your site live in as little as 1-2 weeks. Explore options at /rapid-website-development.`,
    'outsource|backend|frontend': `Scale your development capabilities with our expert, dedicated teams. We offer flexible engagement models:\n\n• Dedicated Teams\n• Staff Augmentation\n• Project-Based Solutions\n\nWe provide access to top-tier talent in technologies like React, Next.js, Node.js, Python, and more. Extend your team at /backend-frontend-outsource.`,
    'whatsapp|chatbot': `Automate customer conversations with AI-powered WhatsApp Chatbots. We help you provide 24/7 support, generate leads, and even process orders directly in WhatsApp, engaging customers where they are most active. Learn more at /whatsapp-chatbots.`,
    'consulting': `Navigate the complexities of the digital landscape with our Digital Business Consulting. We provide strategic guidance on:\n\n• Digital Transformation Roadmaps\n• Technology Stack Advisory\n• Market Entry & Growth Strategy\n\nLet us be your strategic partner in digital growth. See more at /digital-business-consulting.`,
    'digital branding': `Craft a consistent and compelling brand identity across all your digital touchpoints. We focus on:\n\n• Online Brand Identity\n• Digital Content Strategy\n• Brand Voice & Messaging\n\nBuild a brand that thrives online. See our approach at /digital-branding.`,
    'digital transformation': `Modernize your operations and automate processes to stay ahead of the curve. Our services include:\n\n• Legacy System Modernization\n• Business Process Automation\n• Cloud Migration & Strategy\n\nEvolve your business for the digital age at /digital-transformation.`,
    'ott': `Launch your own branded streaming service. Our Over-The-Top (OTT) platform services empower you to build your own "Netflix-like" service. We handle:\n\n• Custom OTT App Development (iOS, Android, Roku, etc.)\n• VOD & Live Streaming solutions\n• Monetization Models (Subscription, Ads, Pay-per-view)\n\nLaunch your streaming empire with us. Learn more at /ott-services.`,
    'broadcast': `We provide end-to-end broadcast solutions to engineer the future of media delivery. Our core services include:\n\n• Playout & Automation\n• Live Streaming & Encoding\n• Media Asset Management (MAM)\n• Broadcast Infrastructure design\n\nPower your media operation at /broadcast-solutions.`,
    'podcast|digital tv|nexstar insights': `Our podcast, "Nexstar Insights," is your weekly dose of digital marketing trends, strategies, and success stories. We also have "Nexstar Bharat" coming soon. You can find our latest episodes, watch video versions, and subscribe on your favorite platform. Explore it all on our Digital TV page at /podcast.`,
    'services|what do you do|offer': `We offer a wide range of services to help your business grow:\n\n- Social Media Marketing\n- Creative & Branding\n- B2B Marketing\n- Search Marketing (SEO/SEM)\n- Video Production\n- E-commerce & Website Development\n- Mobile App Development\n- Augmented Reality\n- Performance Marketing\n- Digital Transformation & Consulting\n\nYou can see all of them at /services.`,
    'contact|reach out|email|phone|address|location': "You can contact us via:\n\nEmail: contact@nexstarlive.com\nPhone (India): +91-9821000921\nPhone (US): +1-917-6721794",
    'pricing|cost|rates': "We have pricing pages for some of our key services. You can find them here:\n\n• SEO Pricing (/pricing/seo-pricing)\n• SMO Pricing (/pricing/smo-pricing)\n• PPC Pricing (/pricing/ppc-pricing)\n\nFor anything else, please reach out via the /contact page.",
    'story|about us|who are you|history|company': "We are Nexstar Media, a premier IT & Media company founded in 2019. As the flagship company of Nexstar Live LLC, US, we specialize in digital media solutions, development, and IT services for an international clientele. You can learn more about our journey, values, and team at /story.",
    'portfolio|work|case studies|examples|projects': "You can see examples of our work and successful projects in our portfolio. We showcase case studies in areas like Blockchain, UI/UX Design, IT Consultancy, and Data Analytics. Explore our work at /portfolio.",
    'inquiry|enquiry': "For any inquiries or to fill out an enquiry form, please email our team at atul@nexstarmedia.in. We'll be happy to assist you.",
    'engagement model': "We offer flexible engagement models to fit your specific needs, including Dedicated Teams, Staff Augmentation, and Project-Based work. We can discuss which model is the best fit during a consultation.",
    'technology|stack|specialize in': "Our team has expertise in a wide range of modern technologies, including React, Next.js, Node.js, Python, Java, and native mobile development with Swift & Kotlin. We can match the right expertise to your tech stack.",
    'code quality|security': "We follow industry best practices, including regular code reviews, automated testing, and strict coding standards. Security is integrated into every stage of our development lifecycle, from design to deployment.",
    'communication|time zone': "We use agile methodologies with regular stand-ups, demos, and retrospectives. Our project managers ensure clear and constant communication via tools like Slack, Jira, and video conferencing. We establish overlapping work hours to ensure seamless collaboration regardless of time zone.",
    'branding package': "Our typical branding package includes brand strategy, logo design (with variations), color palette, typography selection, and a comprehensive brand style guide. We can also include elements like business card design or social media templates based on your needs.",
    'branding process|how long': "A full branding project usually takes 4-8 weeks, depending on scope and complexity. This includes research, strategy, design exploration, revisions, and final delivery of all assets.",
    'rebrand|re-brand': "Absolutely. We specialize in brand refreshes and complete rebrands. We'll start by auditing your current brand and market position to develop a strategy that honors your heritage while positioning you for future growth.",
    'initial design|don\'t like': "Our process is highly collaborative and includes several rounds of revisions. We present multiple initial concepts and work closely with you to refine the chosen direction until it perfectly aligns with your vision.",
    'app cost|how much': "App development costs vary greatly depending on complexity, features, and platform. After an initial consultation to understand your requirements, we provide a detailed, custom quote for your project.",
    'app development time|how long': "A typical mobile app project can take anywhere from 3 to 9 months. This includes discovery, design, development, testing, and launch. We'll create a detailed project timeline once the scope is finalized.",
    'ios and android|both platforms': "Yes, we offer native development for both iOS (Swift) and Android (Kotlin) to provide the best performance and user experience. We also offer cross-platform solutions like React Native for faster time-to-market.",
    'app store|submit': "Absolutely. Our service includes managing the entire submission process for both the Apple App Store and Google Play Store, ensuring your app meets all guidelines and is successfully launched.",
    'orm results|reputation management time': "Building a positive reputation takes time. You can often see initial improvements within 1-3 months. Significant, lasting changes in search results and overall brand sentiment can take 6-12 months of consistent effort.",
    'remove negative reviews|articles': "Removing content is often difficult. Our primary strategy is not removal, but suppression. We work to create and promote a wealth of positive, authoritative content that pushes negative items further down in search results, making them much less visible.",
    'seo vs orm': "SEO (Search Engine Optimization) focuses on ranking your website for specific keywords. ORM (Online Reputation Management) is broader; it's about managing the entire search results page for your brand name to ensure the overall sentiment is positive.",
    'orm ongoing': "Reputation is dynamic and requires continuous attention. While we can manage a specific crisis, we strongly recommend an ongoing ORM strategy to proactively monitor your brand and cultivate positive reviews.",
    'what is performance marketing': "Performance marketing is a form of digital advertising where businesses only pay when a specific action is completed, such as a click, a lead, or a sale. It's a results-driven approach that focuses on measurable ROI.",
    'performance marketing results|time': "With paid campaigns, you can start seeing traffic and results almost immediately. However, achieving optimal performance and a high ROI typically takes 1-3 months as we gather data, test, and refine your campaigns.",
    'performance marketing budget|cost': "Your budget will depend on your industry, goals, and competition. We work with you to establish a starting budget and a strategy to scale it effectively as we start generating a positive return.",
    'performance marketing platforms': "We are experts across a wide range of platforms, including Google Ads (Search, Display, Shopping), Meta (Facebook & Instagram), LinkedIn Ads, and major affiliate networks.",
    'seo vs sem': "SEO (Search Engine Optimization) involves optimizing your website to get 'free,' organic traffic from search engines. SEM (Search Engine Marketing) is a broader term that includes SEO as well as paid advertising methods like Pay-Per-Click (PPC). We combine both for a comprehensive strategy.",
    'seo results|time': "SEO is a long-term strategy. While some improvements can be seen in a few weeks, it typically takes 4-6 months to see significant, sustainable results in rankings and organic traffic.",
    'ppc worth it': "Absolutely. PPC offers immediate visibility and highly targeted traffic. It's an excellent way to generate leads and sales quickly while your long-term SEO strategy is building momentum. We focus on optimizing campaigns for a high Return On Ad Spend (ROAS).",
    'measure success|kpis': "We track a variety of Key Performance Indicators (KPIs), including keyword rankings, organic traffic, click-through rates (CTR), conversion rates, cost per acquisition (CPA), and overall ROI. We provide detailed monthly reports.",
    'social media platforms': "The best platforms depend on your target audience and industry. We conduct thorough research to identify where your customers are most active, whether it's Instagram, LinkedIn for B2B, or TikTok.",
    'social media roi': "We track key performance indicators (KPIs) like engagement rate, reach, website clicks, lead generation, and ultimately, sales conversions. We use custom tracking and analytics to tie social media activity directly to your business goals.",
    'how often post|posting frequency': "Our posting frequency is based on a custom strategy for each platform. We'll develop a content calendar that ensures a steady stream of high-quality content to keep your audience engaged.",
    'social media customer service': "Yes, community management is a core part of our service. We handle comments, messages, and reviews promptly and professionally.",
    'video types|produce': "We produce a wide range of videos, including corporate brand films, TV commercials, social media content, animated explainer videos, product demonstrations, customer testimonials, and event coverage.",
    'video cost|how much': "Video production costs vary widely based on concept complexity, filming duration, location, and post-production needs. We provide custom quotes after a detailed consultation.",
    'video production process': "Our process is collaborative and structured in three phases: 1) Pre-production (strategy, concept, scriptwriting), 2) Production (filming), and 3) Post-production (editing, graphics, final delivery).",
    'website time|how long': "The timeline depends on the complexity. A standard site can take 4-6 weeks, while a custom e-commerce site may take 8-12 weeks or more. We'll provide a detailed timeline after the discovery phase.",
    'website cost|how much': "Website costs vary widely. We provide custom quotes based on your specific needs and can work with you to find a solution that fits your budget.",
    'update website myself': "Yes. We typically build websites on a Content Management System (CMS) like WordPress, which allows you to easily update content. We provide training to ensure you're comfortable managing your site.",
    'ongoing support|maintenance': "Absolutely. We offer a range of support and maintenance packages to keep your website secure, updated, and running smoothly. We see ourselves as your long-term digital partner.",
    'chatbot integrate crm': "Yes, we can integrate your WhatsApp chatbot with most major CRMs (like Salesforce, HubSpot) and e-commerce platforms to automate lead capture, customer support, and sales processes.",
    'chatbot time|how long': "A basic chatbot can be deployed in 2-4 weeks. More complex bots with advanced integrations may take longer. We'll provide a detailed timeline after understanding your requirements.",
    'whatsapp policy|compliant': "Absolutely. We build all our chatbots in strict adherence to the WhatsApp Business Platform policies to ensure your account remains in good standing.",
    'chatbot understand': "We design our chatbots with a 'human handover' protocol. When the bot encounters a query it cannot answer, it can seamlessly transfer the conversation to a live agent.",
    'digital transformation definition': "Digital transformation is the process of integrating digital technology into all areas of a business, fundamentally changing how you operate and deliver value to customers. It's also a cultural change that requires organizations to continually challenge the status quo.",
    'digital transformation start': "Our process begins with a comprehensive audit of your current processes and goals. From there, we work with you to create a prioritized roadmap that focuses on high-impact areas for transformation.",
    'digital transformation for who': "Not at all. Businesses of all sizes can benefit. For small businesses, it can be about adopting cloud-based tools to improve efficiency. For larger companies, it might be a more comprehensive overhaul of legacy systems. We tailor our approach to your size and needs.",
    'change management': "Change management is a critical component of our digital transformation services. We work with your team to ensure clear communication, provide thorough training, and demonstrate the value of new processes and tools to foster adoption.",
    'digital branding vs branding': "While traditional branding sets the overall strategy and identity, digital branding focuses specifically on how your brand is expressed and experienced online. This includes your website, social media, and digital content.",
    'digital brand guide': "A digital brand guide is essential for maintaining consistency online. It provides clear rules for using your logo, colors, fonts, and brand voice in a digital context. This consistency is crucial for building a strong, recognizable, and trustworthy brand.",
    'adapt brand for digital': "Absolutely. A core part of our service is helping established brands translate their identity effectively to the digital world. We'll analyze your existing brand and create a strategy to ensure it thrives online.",
    'digital branding seo': "A strong, consistent digital brand builds authority and trust, which are positive signals for search engines. Consistent branding across your website and social media strengthens your digital footprint and can improve your rankings.",
    'what is digital business consulting': "It's a strategic service designed to help businesses leverage technology and digital channels to achieve their goals. This includes developing digital transformation roadmaps, advising on technology stacks, and improving operational efficiency.",
    'consulting benefit': "Our consulting services can help you identify new growth opportunities, optimize your processes, gain a competitive edge, and ensure a higher ROI on your technology investments.",
    'who is consulting for': "Our consulting services are for any business looking to harness the power of digital, from startups planning their technology foundation to established enterprises seeking to modernize.",
    'consulting engagement start': "We begin with a deep-dive discovery session to understand your business, challenges, and objectives. Based on this, we prepare a detailed proposal outlining the scope, deliverables, and timeline.",
    'ecommerce platform choice': "The best platform depends on your needs. Shopify is excellent for ease of use, while WooCommerce (with WordPress) offers greater flexibility. We'll help you choose during our initial consultation.",
    'ecommerce build time': "A typical e-commerce project takes between 6 to 12 weeks, depending on complexity, design, and custom features required. We'll provide a detailed timeline after our discovery phase.",
    'migrate ecommerce store': "Absolutely. We offer seamless migration services from platforms like Magento, BigCommerce, or any other system to Shopify or WooCommerce, ensuring no loss of data or SEO rankings.",
    'ecommerce support': "Yes, we offer ongoing support and maintenance packages to ensure your store remains secure, up-to-date, and performing at its best.",
    'what is broadcast automation': "Broadcast automation involves using technology to automate the process of playing out television or radio content. This includes scheduling programs and commercials, ensuring a seamless and error-free broadcast 24/7.",
    'handle live event streaming': "Yes, we specialize in high-quality, low-latency live streaming for a variety of events, including sports, news conferences, and corporate town halls. We manage the entire workflow from encoding to delivery.",
    'what is media asset management|mam': "MAM is a system for managing large volumes of media files (video, audio, images). It helps broadcasters organize, search, retrieve, and distribute their content efficiently.",
    'broadcast system support': "Absolutely. We offer comprehensive support and maintenance packages to ensure your broadcast infrastructure runs smoothly.",
    'what is ott': 'OTT (Over-The-Top) refers to the delivery of video content directly to viewers over the internet, bypassing traditional cable or satellite providers. Examples include Netflix, Hulu, and Disney+. We help you build your own branded streaming service.',
    'ott devices': "We develop for a wide range of devices to ensure you can reach your audience everywhere. This includes smartphones (iOS & Android), web browsers, smart TVs (Apple TV, Android TV), and streaming devices like Roku and Amazon Fire TV.",
    'ott monetization|make money': "We can implement several monetization strategies: Subscription VOD (SVOD) like Netflix, Ad-supported VOD (AVOD) like YouTube, or Transactional VOD (TVOD) where users pay for specific content. We can also combine these models.",
    'ott security|drm': "Yes, security is a top priority. We implement Digital Rights Management (DRM) and robust security measures to protect your valuable content from piracy and unauthorized access.",
    'query|question|faq': "I can answer many frequently asked questions. Please type your question, and I'll do my best to help.",
    'hello|hi|hey': "Hello! I'm the Nexstar site assistant. How can I help you today? You can ask me about our services, pricing, or how to contact us.",
};

/**
 * Handles the chat interaction by checking for keywords in the user's message.
 * @param message The user's message.
 * @returns A pre-written response if a keyword is found, otherwise a default message.
 */
export async function chat(message: string): Promise<string> {
    const defaultResponse = "For detailed information, please contact our team at atul@nexstarmedia.in. We'll be happy to assist you.";
    const normalizedMessage = message.toLowerCase();

    for (const pattern in cannedResponses) {
        // Create a regex from the pattern string. 'i' flag makes it case-insensitive.
        const regex = new RegExp(pattern, 'i');
        if (regex.test(normalizedMessage)) {
            return cannedResponses[pattern];
        }
    }

    return defaultResponse;
}

    